### ISSUE TITLE
Can't be used in Swift on non-main thread

### ISSUE THREAD

**Issue by AshStefanOltmann** [appmattus/crypto#25]
Using Swifts async/await feature and `Task.detached {}` I load some files in the background where I want to calculate the checksum for.

My code looks like this:

```
                do {

                    let digest = Algorithm.XXH3_128().createDigest().platform()

                    let data = try Data(contentsOf: URL(fileURLWithPath: photo.url))

                    return digest.digest(input_: data)

                } catch {
                    Log.error("Failed creating checksum", error: error)
                }
```

If I execute that a `IncorrectDereferenceException` occurs as follows:
```
Uncaught Kotlin exception: kotlin.native.IncorrectDereferenceException: Trying to access top level value not marked as @ThreadLocal or @SharedImmutable from non-main thread
    at 0   shared                              0x000000010f091b9d ThrowIncorrectDereferenceException + 93
    at 1   shared                              0x000000010f6ffd9b kfun:com.appmattus.crypto.internal.core.xxh3#XXH3_128bits_reset(com.appmattus.crypto.internal.core.xxh3.XXH3_state_s){}com.appmattus.crypto.internal.core.xxh3.XXH_errorcode + 171
    at 2   shared                              0x000000010f6f7833 kfun:com.appmattus.crypto.internal.core.xxh3.XXH3_128#reset(){} + 435
    at 3   shared                              0x000000010f6f7104 kfun:com.appmattus.crypto.internal.core.xxh3.XXH3_128#<init>(com.appmattus.crypto.Algorithm.XXH3_128){} + 276
    at 4   shared                              0x000000010f2acde5 kfun:com.appmattus.crypto.internal.CoreDigest#create(com.appmattus.crypto.Algorithm){}com.appmattus.crypto.Digest<*> + 18277
```

It works if I wrap that into `DispatchQueue.main.async {}` which of course causes my UI to hang.

This relates to Kotlin/Native memory model.

Maybe you can see if you can fix it in a way that it can be used on background threads. :)

**Comment by mattmook** [comment]
hey @AshStefanOltmann, yes I'll take a look and see what can be achieved. There's definitely no reason why this shouldn't work; my naivety of creating a simple sample app that does its work on the main thread doesn't help.

**Comment by mattmook** [comment]
having looked at the code for XXH3 I wonder if this is more of an issue with my implementation of this particular algorithm.

I'm curious, and need to test if the same issue occurs with the other algorithms. Indeed, I need to add tests to ensure all the algorithms work as expected under this scenario.

**Comment by AshStefanOltmann** [comment]
@mattmook I haven't looked into the source.
Does your implementation threads or does it something in parallel?

In Swift if an object was created on the main thread/dispatcher/actor it can't be used on another thread.

If a object is shared between two threads and if it is not mutable this can be resolved by adding the SharedImmutable annotation. This tells Kotlin/Native that access is okay, because the state will not change.
Similar to this the ThreadLocal annotation will create a copy for each thread - this is no problem if nothing is mutable here.

If your implementation needs to share a mutable state between two threads it will not work that way with the current Kotlin/Native memory model and can only be used on one thread - normally the main thread.

**Comment by mattmook** [comment]
Yes this is exactly what I was thinking that there is an object created on a main thread in this particular algo that needs to be annotated where most of the other implementations don’t have such an impl.

Now holidays are over I’ve got a bit more time to set up a fix for this.

**Comment by AshStefanOltmann** [comment]
@mattmook I tested it in my real project and it works. 👍 Thank you!
This lib is really amazing, so fast and useful. You did a great job here! 💯
