### ISSUE TITLE
Not found on Maven Central

### ISSUE THREAD

**Issue by Wavesonics** [appmattus/crypto#46]
Not sure whats up, my project includes ton of libs from maven central, but this lib can't be resolved for some reason:

`:desktop:jvmMain: Could not resolve com.appmattus.crypto:cryptohash:0.10.1.`

But, obviously it's there:
https://central.sonatype.com/artifact/com.appmattus.crypto/cryptohash/0.10.1/overview

**Comment by mattmook** [comment]
weird. it appears to be working for me in the sample app when I point to the dependency from maven central.

are you able to provide some of your code of how the dependency is added?


I'm also in the process of updating the projects dependencies and as part of that upgrading the upload process; we can see if that helps too although no reason it shouldn't work currently

**Comment by Wavesonics** [comment]
I apparently just had something strange going on, it syncs perfectly fine now, sorry about that!

**Comment by mattmook** [comment]
No worries
